#服务器端口
server:
  port: 8004

#服务器名称
spring:
  application:
    name: ConfigServer

#子服务器配置地址---------配置服务器专属！！
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/yml/   #搜索src/main/resource下的yml文件夹下的文件

#服务器id地址
eureka:
  instance:
    hostname: 127.0.0.1

#注册服务器地址
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8000/eureka/